// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArlgQzCpEi0NlXrMwndeWnqZAYnIpmIQo',
    appId: '1:60517230143:web:edcb0b33e4c9eb38a4fa8a',
    messagingSenderId: '60517230143',
    projectId: 'popcorn-b9f73',
    authDomain: 'popcorn-b9f73.firebaseapp.com',
    storageBucket: 'popcorn-b9f73.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiZ5wazr-0EQxOTPpXaTSTYVQukyAQcyo',
    appId: '1:60517230143:android:9ae1a3bdd46f88caa4fa8a',
    messagingSenderId: '60517230143',
    projectId: 'popcorn-b9f73',
    storageBucket: 'popcorn-b9f73.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4ONd_qmu_ieSnbi3tYO1lowJjtGaxazk',
    appId: '1:60517230143:ios:b2db0623e70fbcfda4fa8a',
    messagingSenderId: '60517230143',
    projectId: 'popcorn-b9f73',
    storageBucket: 'popcorn-b9f73.appspot.com',
    iosBundleId: 'com.example.popcorn1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4ONd_qmu_ieSnbi3tYO1lowJjtGaxazk',
    appId: '1:60517230143:ios:3b945ab8e3b4c83ba4fa8a',
    messagingSenderId: '60517230143',
    projectId: 'popcorn-b9f73',
    storageBucket: 'popcorn-b9f73.appspot.com',
    iosBundleId: 'com.example.popcorn1.RunnerTests',
  );
}
